// Code generated by protoc-gen-gin. DO NOT EDIT.

package proto

import (
	gin "github.com/gin-gonic/gin"
	http "net/http"
)

type AddressHttpServer struct {
	server AddressServer
	router gin.IRouter
}

func RegisterAddressServerHTTPServer(srv AddressServer, r gin.IRouter) {
	s := AddressHttpServer{
		server: srv,
		router: r,
	}
	s.RegisterService()
}

func (s *AddressHttpServer) GetAddressList_0(c *gin.Context) {
	var in AddressRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GetAddressList(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *AddressHttpServer) CreateAddress_0(c *gin.Context) {
	var in AddressRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.CreateAddress(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *AddressHttpServer) DeleteAddress_0(c *gin.Context) {
	var in AddressRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.DeleteAddress(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *AddressHttpServer) UpdateAddress_0(c *gin.Context) {
	var in AddressRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.UpdateAddress(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *AddressHttpServer) RegisterService() {

	s.router.Handle("POST", "", s.GetAddressList_0)

	s.router.Handle("POST", "", s.CreateAddress_0)

	s.router.Handle("POST", "", s.DeleteAddress_0)

	s.router.Handle("POST", "", s.UpdateAddress_0)

}
