// Code generated by protoc-gen-gin. DO NOT EDIT.

package proto

import (
	gin "github.com/gin-gonic/gin"
	http "net/http"
)

type UserFavHttpServer struct {
	server UserFavServer
	router gin.IRouter
}

func RegisterUserFavServerHTTPServer(srv UserFavServer, r gin.IRouter) {
	s := UserFavHttpServer{
		server: srv,
		router: r,
	}
	s.RegisterService()
}

func (s *UserFavHttpServer) GetFavList_0(c *gin.Context) {
	var in UserFavRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GetFavList(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserFavHttpServer) AddUserFav_0(c *gin.Context) {
	var in UserFavRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.AddUserFav(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserFavHttpServer) DeleteUserFav_0(c *gin.Context) {
	var in UserFavRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.DeleteUserFav(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserFavHttpServer) GetUserFavDetail_0(c *gin.Context) {
	var in UserFavRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GetUserFavDetail(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *UserFavHttpServer) RegisterService() {

	s.router.Handle("POST", "", s.GetFavList_0)

	s.router.Handle("POST", "", s.AddUserFav_0)

	s.router.Handle("POST", "", s.DeleteUserFav_0)

	s.router.Handle("POST", "", s.GetUserFavDetail_0)

}
