// Code generated by protoc-gen-gin. DO NOT EDIT.

package proto

import (
	gin "github.com/gin-gonic/gin"
	http "net/http"
)

type MessageHttpServer struct {
	server MessageServer
	router gin.IRouter
}

func RegisterMessageServerHTTPServer(srv MessageServer, r gin.IRouter) {
	s := MessageHttpServer{
		server: srv,
		router: r,
	}
	s.RegisterService()
}

func (s *MessageHttpServer) MessageList_0(c *gin.Context) {
	var in MessageRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.MessageList(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *MessageHttpServer) CreateMessage_0(c *gin.Context) {
	var in MessageRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.CreateMessage(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *MessageHttpServer) RegisterService() {

	s.router.Handle("POST", "", s.MessageList_0)

	s.router.Handle("POST", "", s.CreateMessage_0)

}
