// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int"; DO NOT EDIT.

package code

// init register error codes defines in this source code to `imooc/mxshop/pkg/errors`
func init() {
	register(ErrRecordNotFound, 404, "Record not found")
	register(ErrMessageQuery, 500, "Failed to query Message from Database")
	register(ErrMessageCreate, 500, "Failed to create Message in Database")
	register(ErrGoodsNotFound, 404, "Goods not found")
	register(ErrCategoryNotFound, 404, "Category not found")
	register(ErrEsUnmarshal, 500, "Elasticsearch unmarshal error")
	register(ErrBannerNotFound, 404, "Banner not found")
	register(ErrBrandNotFound, 404, "Brand not found")
	register(ErrCategoryBrandNotFound, 404, "CategoryBrand not found")
	register(ErrGoodsImageNotFound, 404, "GoodsImage not found")
	register(ErrJsonUnmarshal, 500, "JSON unmarshal error")
	register(ErrInventoryNotFound, 404, "Inventory not found")
	register(ErrInvSellDetailNotFound, 404, "Inventory sell detail not found")
	register(ErrInvNotEnough, 400, "Inventory not enough")
	register(ErrOptimisticRetry, 500, "Optimistic lock retry limit exceeded")
	register(ErrShopCartItemNotFound, 404, "ShopCart item not found")
	register(ErrSubmitOrder, 500, "Failed to submit order")
	register(ErrNoGoodsSelect, 400, "No goods selected")
	register(ErrOrderNotFound, 404, "Order not found")
	register(ErrOrderStatus, 500, "Failed to update order status")
	register(ErrInvalidParameter, 400, "Invalid request parameter")
	register(ErrUserNotFound, 404, "User not found")
	register(ErrUserPasswordIncorrect, 401, "User password incorrect")
	register(ErrCodeNotExist, 404, "Verification code not exist")
	register(ErrCodeInCorrect, 400, "Verification code incorrect")
	register(ErrUserAlreadyExists, 400, "User already exists")
	register(ErrSmsSend, 500, "Failed to send SMS")
	register(ErrForbidden, 403, "User privilege insufficient")
	register(ErrUnauthorized, 401, "User not logged in")
	register(ErrInvalidUserID, 400, "Invalid user ID format")
	register(ErrRoleNotConfigured, 500, "User role not configured")
	register(ErrInvalidRoleFormat, 400, "Invalid role format")
	register(ErrInvalidRole, 403, "Invalid role value, only 1(admin) or 2(user) allowed")
}
