// Code generated by protoc-gen-gin. DO NOT EDIT.

package proto

import (
	gin "github.com/gin-gonic/gin"
	http "net/http"
	"strconv"
	"github.com/golang/protobuf/ptypes/empty"

)

type GoodsHttpServer struct {
	server GoodsServer
	router gin.IRouter
}

func RegisterGoodsServerHTTPServer(srv GoodsServer, r gin.IRouter) {
	s := GoodsHttpServer{
		server: srv,
		router: r,
	}
	s.RegisterService()
}

func (s *GoodsHttpServer) GoodsList_0(c *gin.Context) {
	var in GoodsFilterRequest

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GoodsList(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) BatchGetGoods_0(c *gin.Context) {
	var in BatchGoodsIdInfo

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.BatchGetGoods(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) CreateGoods_0(c *gin.Context) {
	var in CreateGoodsInfo

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.CreateGoods(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) DeleteGoods_0(c *gin.Context) {
	var in DeleteGoodsInfo

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)


	out, err := s.server.DeleteGoods(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) UpdateGoods_0(c *gin.Context) {
	var in CreateGoodsInfo

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.UpdateGoods(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) GetGoodsDetail_0(c *gin.Context) {
	var in GoodInfoRequest

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.GetGoodsDetail(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) GetAllCategorysList_0(c *gin.Context) {
	in := empty.Empty{}

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.GetAllCategorysList(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) GetSubCategory_0(c *gin.Context) {
	var in CategoryListRequest

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.GetSubCategory(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) CreateCategory_0(c *gin.Context) {
	var in CategoryInfoRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.CreateCategory(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) DeleteCategory_0(c *gin.Context) {
	var in DeleteCategoryRequest

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.DeleteCategory(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) UpdateCategory_0(c *gin.Context) {
	var in CategoryInfoRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.UpdateCategory(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) BrandList_0(c *gin.Context) {
	var in BrandFilterRequest

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.BrandList(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) CreateBrand_0(c *gin.Context) {
	var in BrandRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.CreateBrand(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) DeleteBrand_0(c *gin.Context) {
	var in BrandRequest

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.DeleteBrand(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) UpdateBrand_0(c *gin.Context) {
	var in BrandRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.UpdateBrand(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) BannerList_0(c *gin.Context) {
	in := empty.Empty{}

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.BannerList(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) CreateBanner_0(c *gin.Context) {
	var in BannerRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.CreateBanner(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) DeleteBanner_0(c *gin.Context) {
	var in BannerRequest

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.DeleteBanner(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) UpdateBanner_0(c *gin.Context) {
	var in BannerRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.UpdateBanner(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) CategoryBrandList_0(c *gin.Context) {
	var in CategoryBrandFilterRequest

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.CategoryBrandList(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) GetCategoryBrandList_0(c *gin.Context) {
	var in CategoryInfoRequest

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.GetCategoryBrandList(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) CreateCategoryBrand_0(c *gin.Context) {
	var in CategoryBrandRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.CreateCategoryBrand(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) DeleteCategoryBrand_0(c *gin.Context) {
	var in CategoryBrandRequest

	if err := c.ShouldBindQuery(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.DeleteCategoryBrand(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) UpdateCategoryBrand_0(c *gin.Context) {
	var in CategoryBrandRequest

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

		atoi, err := strconv.Atoi(c.Params.ByName("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	in.Id = int32(atoi)

	out, err := s.server.UpdateCategoryBrand(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *GoodsHttpServer) RegisterService() {

	s.router.Handle("GET", "/g/v1/good/list", s.GoodsList_0)

	s.router.Handle("POST", "/g/v1/good/batch", s.BatchGetGoods_0)

	s.router.Handle("POST", "/g/v1/good", s.CreateGoods_0)

	s.router.Handle("DELETE", "/g/v1/good/:id", s.DeleteGoods_0)

	s.router.Handle("PUT", "/g/v1/good/:id", s.UpdateGoods_0)

	s.router.Handle("GET", "/g/v1/good/:id", s.GetGoodsDetail_0)

	s.router.Handle("GET", "/g/v1/categorys", s.GetAllCategorysList_0)

	s.router.Handle("GET", "/g/v1/categorys/:id", s.GetSubCategory_0)

	s.router.Handle("POST", "/g/v1/categorys", s.CreateCategory_0)

	s.router.Handle("DELETE", "/g/v1/categorys/:id", s.DeleteCategory_0)

	s.router.Handle("PUT", "/g/v1/categorys/:id", s.UpdateCategory_0)

	s.router.Handle("GET", "/g/v1/brands", s.BrandList_0)

	s.router.Handle("POST", "/g/v1/brands", s.CreateBrand_0)

	s.router.Handle("DELETE", "/g/v1/brands/:id", s.DeleteBrand_0)

	s.router.Handle("PUT", "/g/v1/brands/:id", s.UpdateBrand_0)

	s.router.Handle("GET", "/g/v1/banners", s.BannerList_0)

	s.router.Handle("POST", "/g/v1/banners", s.CreateBanner_0)

	s.router.Handle("DELETE", "/g/v1/banners/:id", s.DeleteBanner_0)

	s.router.Handle("PUT", "/g/v1/banners/:id", s.UpdateBanner_0)

	s.router.Handle("GET", "/g/v1/categorybrands", s.CategoryBrandList_0)

	s.router.Handle("GET", "/g/v1/categorybrands/:id", s.GetCategoryBrandList_0)

	s.router.Handle("POST", "/g/v1/categorybrands", s.CreateCategoryBrand_0)

	s.router.Handle("DELETE", "/g/v1/categorybrands/:id", s.DeleteCategoryBrand_0)

	s.router.Handle("PUT", "/g/v1/categorybrands/:id", s.UpdateCategoryBrand_0)

}
